version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      # these are REQUIRED to be mounted or else bugs could occur since these
      # folders do not exist internally
      - ./bundles:/app/bundles
      - ./mods:/app/mods
    env_file:
      - .env.local
