name: Docker build workflow
on:
  push:
    branches:
      - 'master'
      - 'alpha/*'

jobs:
  verify:
    uses: ./.github/workflows/verify-reusable.yml

  # from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
  release-to-docker:
    runs-on: ubuntu-latest
    needs: 'verify'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{ secrets.DOCKER_IMAGES }}

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
